name: Deploy Docker App
 ##
on:
  push:
    branches:
      - main
 
jobs:
  deploy:
    runs-on: self-hosted
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Stop old container
        run: |
          docker stop my-app || true
          docker rm my-app || true
 
      - name: Build Docker image
        run: |
          docker build -t my-app:latest .
 
      - name: Start new container
        run: |
          docker run -d \
            --name my-app \
            -p 3000:3000 \
            my-app:latest
